### ISSUE TITLE
Deprecated method

### ISSUE THREAD

**Issue by xtingray** [momesana/de-casteljau_algorithm_demo#1]
Hi,
When I compiled the source code using Qt 5.15.2, got a warning message related to the deprecated method "mapped". I just changed it to "mappedString" and the warning disappeared.  Great implementation, by the way!
    diff --git a/src/mainwindow.cpp b/src/mainwindow.cpp
    index 4c1b5bd..e799e3f 100644
    --- a/src/mainwindow.cpp
    +++ b/src/mainwindow.cpp
    @@ -108,7 +108,7 @@ void MainWindow::setupConnections()
            connect(btn, &ColorToolButton::clicked, signalMapper, qOverload<>(&QSignalMapper::map));
            signalMapper->setMapping(btn, btnKeyMap.value(btn));
         }
    -    connect(signalMapper, qOverload<const QString&>(&QSignalMapper::mapped), [this, settings, btnKeyMap](const 
    QString& configKey){
    +    connect(signalMapper, qOverload<const QString&>(&QSignalMapper::mappedString), [this, settings, btnKeyMap](const 
    QString& configKey){
            const QColor initialColor = settings->value(configKey, QColor(Qt::white)).value<QColor>();
            const QColor selectedColor = QColorDialog::getColor(initialColor, this, tr("Select Color"));
           if (selectedColor.isValid()) {

**Comment by momesana** [comment]
Thank you, xtingray, for reporting the issue. I've just confirmed it and will push your fix momentarily.

**Comment by momesana** [comment]
The fix has been pushed to master.

**Comment by momesana** [comment]
The push has been fixed to master.
